### PR TITLE
docs: lowercase almost everything

### LINKED ISSUE #115: 🔡 error message lettercase convention
I am going to _lower_ the letter case of almost every message:
- [x] tutorial
- [x] the severity output
- [x] all examples

### PR DESCRIPTION
**Pull request by favonia**
Close #115.

### CODE REVIEW

**Comment by mikeshulman** [comment]
Is it also recommended for the user that error messages be all lowercase?

**Comment by favonia** [comment]
> Is it also recommended for the user that error messages be all lowercase?

@mikeshulman I haven't made up my mind on this. Lowercase messages seem more "composable" with other things, but I don't feel strongly enough about them to enforce anything. Do you have an opinion about what or what not to do?

**Comment by mikeshulman** [comment]
This is not something that I want to expend any energy on having an opinion about.  I'm already spending more time and energy than I ought to on things like error reporting, parsing, and pretty-printing.  (-:

**Comment by favonia** [comment]
@mikeshulman then it seems that lowercase messages without ending punctuation can't go wrong

**Pull request merged**
