### PR TITLE
feat(Tty): custom markers

### PR DESCRIPTION
**Pull request by favonia**

### CODE REVIEW

**Comment by favonia** [comment]
I'm okay with the current implementation but I'm not sure about the API. With this PR, the `display` function takes a new argument of type
```ocaml
use_ansi:bool -> use_color:bool -> [`End_of_line | `End_of_file] option -> tag MarkedSource.mark -> string
```
that turns a mark into a string. I wonder how "obvious" this type means without reading the documentation.

**Comment by mikeshulman** [comment]
> I wonder how _obvious_ this design is to library users _without reading any documentation?_

My initial reaction is "not very".  (-:

I'm guessing that the output of this function is supposed to be a string like "EOF" or "EOL".  If so, why does it need to know about `use_ansi` and `use_color`?  And what is a `tag MarkedSource.mark`?

**Comment by favonia** [comment]
@mikeshulman Your guess is correct. The reason that `use_ansi` is that a "mark" can also be the start or end of a range. When ANSI control sequences are not used, it will be impossible to mark the ranges without extra symbols. Currently, we are not using any symbols even if ANSI control sequences are not used.

Here's the definition of `mark`:
```ocaml
(** A mark signals the start or end of a non-empty range, or the location of a point (a range of zero width). *)
type 'tag mark = 'tag MarkedSource.mark =
  | RangeBegin of 'tag
  | RangeEnd of 'tag
  | Point of 'tag
```

**Comment by mikeshulman** [comment]
What is the `tag`?

Are all possible combinations of values for the ``[`End_of_line | `End_of_file] option`` and the `tag mark` arguments possible?  E.g. could you have a ``Some `End_of_file`` combined with `RangeBegin`?

**Comment by favonia** [comment]
@mikeshulman Here's the definition of `tag`:
```ocaml
(** The index type of all messages in a diagnostic. *)
type index = MainMessage | ExtraRemark of int

(** A tag consists of an index (of type {!type:index}) and a message (of type {!type:Text.t}) *)
type tag = index * Text.t
```
It should be impossible to have ``Some `End_of_file`` with `RangeBegin`.

From the conversation, I guess my dream of "making the API self-explanatory" failed... but I'm not sure how to improve it.

**Comment by mikeshulman** [comment]
My rule of thumb is that if some combination of arguments is impossible, then the types should prevent that combination from occurring.  Can those two arguments be combined into one, belonging to a datatype that enumerates the exact possibilities, exhaustively and non-overlappingly, with each constructor taking a fully flattened tuple of arguments that doesn't require looking up the definitions of other types to know what it contains?

**Comment by favonia** [comment]
@mikeshulman Good point! I'll need more time to polish it.

Another impossible combination is `~use_ansi:false` and `~use_color:true`. I guess these two can be combined into three options:
- ``Disabled``: No ANSI control sequences.
- ``No_color``: Use ANSI control sequences, but without colors.
- ``Fully_enabled``: Use colors.

PS: for the display function, the same combination (`~use_ansi:false` and `~use_color:true`) is also impossible, but there are 9 combinations there (enable/disable/auto)^2 instead of just 4 (enabled/disabled)^2. I gave up on naming all 8 options...

**Comment by mikeshulman** [comment]
In the display function, in practice would anyone really want any combination other than the four of `Disabled`, `No_color`, `Fully_enabled`, and `Auto`?

**Comment by mikeshulman** [comment]
Ok, I guess 7 is close enough to 3x3 that having two arguments does make sense there.  (-:

**Comment by favonia** [comment]
## Current progress

I hope this type looks better now...
```ocaml
type marker =
  ansi:[ `Enabled_with_color | `Enabled_without_color | `Disabled ]
  -> [ `Main_message | `Extra_remark of int ]
  -> [ `Range_begin
     | `Range_end of [`End_of_line | `End_of_file] option
     | `Point of [`End_of_line | `End_of_file] option
     ]
  -> string
```

## Remaining issues

1. What should be the default range delimiters when ANSI sequences is disabled?
2. Should we allow custom symbols before texts?
   Current style, without any symbols:
   ```
    ￭ /path/to/file
    23 | wwww‹POS›wwwwww‹EOF›
       ^ somewhere in the middle
       ^ ending of another file
   ```
   Alternative style 1:
   ```
    ￭ /path/to/file
    23 | wwww‹POS›wwwwww‹EOF›
       ^ ‹POS›
         somewhere in the middle
       ^ ‹EOF›
         ending of another file
         second line of message
   ```
   Alternative style 2:
   ```
    ￭ /path/to/file
    23 | wwww‹POS›wwwwww‹EOF›
       ^ ‹POS› somewhere in the middle
       ^ ‹EOF› ending of another file
         second line of message
   ```

**Comment by favonia** [comment]
Let me merge this first so that I can work on other radical changes. :sweat_smile:

**Comment by favonia** [comment]
Update: now French double quotation marks (angle quotation marks) are used when ANSI escape sequences are disabled.

**Comment by favonia** [comment]
@mikeshulman Thanks. What constructors would you suggest if the `ansi` argument is not labeled? Would you suggest `[ `Color | `No_color | `No_ansi ]`?

**Comment by mikeshulman** [comment]
Hmm, maybe.  `No_color` is a bit misleading on its own since it doesn't indicate what *should* be used.

**Pull request merged**
